version: '3.7'

services:

  cert-server:
    build:
      context:  ./services/cert_server
      dockerfile: Dockerfile
    volumes:
      - ./services/cert_server/data:/usr/certs
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - SECRET_KEY=$SECRET_KEY
      - OVPN_SERVER_URL=http://ovpn-server:5000

  ovpn-server:
    build:
      context: ./services/ovpn_server
      dockerfile: Dockerfile
    volumes:
      - ./services/ovpn_server/data:/usr/certs
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - CERT_SERVER_URL=http://cert-server:5000
