FROM ubuntu
WORKDIR /usr/src/app
RUN apt update && \
    apt install -y openvpn && \
    apt install -y openssh-client && \
    apt install -y python3

RUN apt install -y python3 python3-pip python3-dev && \
    pip3 install --upgrade pip

RUN apt install -y wget && \
    wget -P /usr/src/certs https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.4/EasyRSA-3.0.4.tgz

WORKDIR /usr/src/certs
RUN tar xvf EasyRSA-3.0.4.tgz && \
    rm EasyRSA-3.0.4.tgz
COPY ./server.conf /etc/openvpn/
COPY ./base.conf /usr/src/app

WORKDIR /usr/src/app
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

ARG EASYRSA_PATH   
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8   

RUN ln -s $EASYRSA_PATH/openssl-easyrsa.cnf /usr/bin/openssl-easyrsa.cnf && \
    ln -s $EASYRSA_PATH/easyrsa /usr/bin/easyrsa && \
    ln -s $EASYRSA_PATH/x509-types /usr/bin/x509-types && \
    ln -s /usr/bin/python3.6 /usr/bin/python

COPY . /usr/src/app
COPY ./certs crt/server.crt[t] /etc/openvpn
COPY ./certs crt/ca.crt[t] /etc/openvpn
COPY ./certs pki/dh.pem[t] /etc/openvpn 

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

CMD ["/usr/src/app/entrypoint.sh"]
